### ISSUE TITLE
Multipart Form Support

### ISSUE THREAD

**Issue by dwclark** [http-builder-ng/http-builder-ng#1]
Add mulitpart form support. Support should be optional and activated if supporting library is present on the classpath (like support for CSV and JSoup). The best library is probably javax.mail 1.5. Different parts should be encoded/parsed using existing parsers and encoders.

**Comment by cjstehno** [comment]
Note: The `javax.activation` framework is actually in the core Java library.

**Comment by cjstehno** [comment]
I broke out the encoder/parser work to a separate issue - this will just be support for form encoding and file upload content support.

**Comment by cjstehno** [comment]
This issue is fixed and a PR has been created.
