### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by cjstehno** [http-builder-ng/http-builder-ng#109]
There have been a few comments about a lack of documentation.

* Figure out what is missing or weak
* Address issues existing or provided by others.
* I have considered a deeper more detailed user guide, maybe it's time to start it.

We may have gotten so deep into the project that we don't notice what's missing.

*If you have any suggestions please add them in the comments*

**Comment by noamt** [comment]
I'd be happy to write up some docs I figured would be useful while preparing my presentations.
Do we want to continue with gh-pages?

**Comment by cjstehno** [comment]
Let's start with some suggestions about what is missing and what the deficiencies are so that we can figure out how best to collaborate.

The web site and user guide content is in the src directory and is rendered into build and then published to gh-pages. I'd like to keep this flow for now. I will document it better in the readme since others may want to build it.

**Comment by cjstehno** [comment]
I updated the Readme on the `development` branch with more details about building the docs.

**Comment by noamt** [comment]
I think part of the issue is that the docs dive straight into the really cool and advanced features, but skips the most basic usages. I mean it goes from `Configuration` to `Authentication` and the right into `Encoders`.

I think we could improve the documentation by easing it in. So perhaps between `Authentication` and `Encoders`, we could have sections of:

1. How to think about a basic request structure. The pattern I've identified, and helped me understand was:
```
def request = HttpBuilder.configure() {
//Configure client here
}
.get() {
//Configure request here
}
```
2. Very plain examples, like "Here's a simple `GET` request" (replace get with all other method types)
3. A detailed explanation of what I can do with the request and response objects. I think this one is most important as the majority of use cases will need to use both of them.

**Comment by cjstehno** [comment]
I agree that the organization of the guide is a bit haphazard. I have been working on what feels like a cleaner outline, which may play well with what you are suggesting:

```
Introduction
History
License
Configuration
    Authentication
        BASIC
        DIGEST
    Interceptors
    Exception Handling
    Ignoring SSL Issues
Request
    Headers
    Cookies
    Encoders
    Body Content
    Multipart
Response
    Parsers
    Body Content
    Multipart
    Success/Failure/When Handlers
Standard Java Usage
Client Library Intgration
Examples
    Resource Last Modified (HEAD)
    Scraping Web Content (GET)
    Sending/Receiving JSON Data (POST)
    Sending Form Data (POST)
    Sending Multipart Data (POST)
```

Where `Configuration` section could have added details about how requests are structured (point 1). The simple examples could be added in the `Request` section as per-verb examples (point 2), while the detailed request/response discussions would be in the `Request` and `Response` sections respectively (point 3).

Does this seem like it would fill in the gaps appropriately?

**Comment by cjstehno** [comment]
Along the lines of what I mentioned above, I have created a `doc-refactor` branch with the user guide broken up in to multiple documents included in the main. At this point the content has been moved around but is basically the same as what's already there with a few TODOs where the new or updated content will live.

I will work on implementing your suggestions over the next few days. Thanks. I appreciate the feedback.

**Comment by cjstehno** [comment]
After digging in a bit, I am deviating from the outline above slightly, but it feels like a better direction.

**Comment by cjstehno** [comment]
I have merged the re-worked User Guide into the `development` branch which will be released soon. I will close this issue, but please feel free to review the new guide when it comes out and create an issue for anything you find that could be expanded upon.
