### ISSUE TITLE
What do we need for 1.0?

### ISSUE THREAD

**Issue by cjstehno** [http-builder-ng/http-builder-ng#113]
This is more of a planning task. We need to document issues for everything we are missing for a 1.0 release.

* Anything with the [1.0 Milestone](https://github.com/http-builder-ng/http-builder-ng/milestone/2) tag should be considered "required for 1.0"

**Comment by dwclark** [comment]
Simple and obvious addition: Support OPTIONS and TRACE

**Comment by cjstehno** [comment]
I will add support for these in Ersatz soon - https://github.com/cjstehno/ersatz/issues/50

**Comment by cjstehno** [comment]
@dwclark I say we finish up a few of these open issues and call our next release 1.0... what do you think?

**Comment by dwclark** [comment]
Sounds good. The main thing is to finish up the remaining http verbs.
That's good enough for 1.0 I think.

**Comment by cjstehno** [comment]
Yeah most of the other stuff is small tweaks or nice to haves. I am going to start working on this stuff again this week so I will do the missing verbs and then roll on through the other odds and ends. If you want to grab anything just assign it to yourself and I will leave it for you.

**Comment by cjstehno** [comment]
I am going to close this meta-issue since we have tickets for all the 1.0 stuff.
