### ISSUE TITLE
Static type checking extension 'typecheckhttpconfig.groovy' was not found

### ISSUE THREAD

**Issue by yoann-trouillet** [http-builder-ng/http-builder-ng#115]
Hi,

I am trying to use http-builder-ng inside a https://grails.org/ app

| Grails Version: 3.2.7
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_121

simply added the below to my gradle config

compile 'io.github.http-builder-ng:http-builder-ng-core:0.15.0'

dependency report looks good

+--- io.github.http-builder-ng:http-builder-ng-core:0.15.0
|    +--- xml-resolver:xml-resolver:1.2
|    \--- org.slf4j:slf4j-api:1.7.21 -> 1.7.22

Howvere I am getting this exception at run time

Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  Script1.groovy: Static type checking extension 'typecheckhttpconfig.groovy' was not found on the classpath.
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  1 error
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1073)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:591)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at groovy.lang.GroovyShell.parse(GroovyShell.java:680)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:662)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:650)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at groovyx.net.http.HttpConfigs$BaseHttpConfig.configure(HttpConfigs.java:525)
Apr 13 11:50:47 WIN-VMNF32G2UHT WEB2:  	at groovyx.net.http.HttpConfigs.<clinit>(HttpConfigs.java:618)

Appreciate any tips or comments you might have.

Thanks for your time
Yoann.

**Comment by cjstehno** [comment]
How are you deploying the application, or are you just running the grails command line? Can you provide a self-contained example of this (tar or project link)? This sounds like #107 - the user was able to pull put a copy of the file on the Tomcat classpath, and then eventually moving to the current version of Tomcat solved the issue. 

Let me know if this sounds like the same issue and if you can provide an example and we can figure out how to move forward.

**Comment by cjstehno** [comment]
**Note to self:** we need to test with Grails and provide documentation of any config, issues, work-arounds. Might not hurt to double-check the current versions of Spring-boot as well.

**Comment by yoann-trouillet** [comment]
Thanks for coming back to me - Yes it's the same issue as #107 - will try to upgrade to a different version of tomcat.

**Comment by cjstehno** [comment]
I will go ahead and close this issue... please let me know if the problem remains after upgrade.
