### ISSUE TITLE
URI query encoded when specified in the request configure block

### ISSUE THREAD

**Issue by fuji23** [http-builder-ng/http-builder-ng#117]
Request uri will be as : https://jsonplaceholder.typicode.com/posts%3FuserId=1

        HttpBuilder.configure({ c -> new ApacheHttpBuilder(c); } as Function) {
            request.uri = 'https://jsonplaceholder.typicode.com/posts?userId=1'
        }.get(Object) {
            response.success {
                println('Success')
            }
        }

        HttpBuilder.configure({ c -> new ApacheHttpBuilder(c); } as Function) {
            request.uri = 'https://jsonplaceholder.typicode.com/'
        }.get(Object) {
            request.uri.path = '/posts?userId=1'

            response.failure {
                println('Failure')
            }
        }

**Comment by fuji23** [comment]
Looks like it's my mistake in 'request.uri.path' instead of 'request.uri'

**Comment by cjstehno** [comment]
Thanks. I will take a look at this soon.

**Comment by cjstehno** [comment]
Actually the query string parameters should be applied using the `setQuery(Map)` method rather than being specified on the `path` since they are separate components of the URI. That being said, I am looking at supporting this style of configuration.

**Comment by cjstehno** [comment]
We will keep the support as-is for now since adding support for that configuration style would be non-optimal, your example could be corrected to be:

```groovy
ApacheHttpBuilder.configure {
    request.uri = 'https://jsonplaceholder.typicode.com/'
}.get(Object) {
    request.uri.path = '/posts'
    request.uri.query = [userId: 1]

    response.failure {
        println 'Failure'
    }
    response.success {
        println 'Success'
    }
}
```

Note that I also simplified your configuration a bit. Please let me know if this does not solve your problem.
