### ISSUE TITLE
Quality analysis tools

### ISSUE THREAD

**Issue by cjstehno** [http-builder-ng/http-builder-ng#124]
FindBugs seems to be dead, and not all that useful. Investigate the integration of [PMD](https://pmd.github.io/) and [CheckStyle](http://checkstyle.sourceforge.net/) instead.

* ensure that they have Gradle plugins
* ensure that their reports can be collected rather than having one per sub-project
* it would be nice if they actually looked good too
* ensure that the configured rules are not annoying (fail the build only on extreme fails)

Are there other tools to consider?

**Comment by TobiX** [comment]
Have you considered SonarQube? There is a cloud-hosted instance: https://about.sonarcloud.io/

**Comment by cjstehno** [comment]
I didn't realize they had free cloud instances. I will check that out. Thanks.

**Comment by cjstehno** [comment]
Swtich from FindBugs to https://spotbugs.github.io/
