### ISSUE TITLE
Please document the dependencies

### ISSUE THREAD

**Issue by twogee** [http-builder-ng/http-builder-ng#136]
I'm trying to run an Artifactory plugin using http-builder-ng. Unfortunately, the plugin fails with

```
java.lang.NoClassDefFoundError: Could not initialize class groovyx.net.http.HttpConfigs
	groovyx.net.http.HttpObjectConfigImpl.<init>(HttpObjectConfigImpl.java:34)
	groovyx.net.http.HttpBuilder.configure(HttpBuilder.java:163)
	groovyx.net.http.HttpBuilder.configure(HttpBuilder.java:139)
```
It looks like `root()` requires that all optional dependencies, opencsv, cyberneko and jsoup, are available or something else goes wrong in `ifClassIsLoaded()`. Artifactory is known for disabling lazy loading, and the issue deserves at least a mention in documentation along with the optional dependencies.

**Comment by cjstehno** [comment]
So artifactory make the optional dependencies required? I am not sure I am fully understanding the issue - other than being more clear about what the optional dependencies are - can you provide a bit more detail?

**Comment by twogee** [comment]
Sorry for a bad description: my current understanding is that `ifClassIsLoaded()` must catch `NoClassDefFoundError`. I need some time for testing, though.
