### ISSUE TITLE
How to set connection timeout

### ISSUE THREAD

**Issue by radarsh** [http-builder-ng/http-builder-ng#139]
Specifically, I would like to set a connection timeout on the Apache implementation. I couldn't find any way to do that by browsing through the code and documentation.

**Comment by cjstehno** [comment]
We currently, don't expose that property... this brings up an interesting problem. There will always be little odds and ends properties of a client that you might want to specify, but we don't want to expose. 

I have created #140 and #141 to address these deficiencies. 

We should hopefully be able to get a release out with these modifications sometime early next week.

I will close this issue in favor of those other two.

**Comment by cjstehno** [comment]
I have addressed this issue and it will be fixed in the next release.
