### ISSUE TITLE
Setting client parameters

### ISSUE THREAD

**Issue by kenwdelong** [http-builder-ng/http-builder-ng#145]
Is there a way to set the underlying client parameters?  I am using the Apache client, and I need to set "http.protocol.handle-redirects".  But I'm not sure how I can do that.

**Comment by cjstehno** [comment]
Assuming this can be done on an instance of the client, I just added a feature to allow client-specific configuration, but it has not been released yet. If't checked into the `development` branch if you want to try it out - let us know if this doesn't do what you want it to. We should be cutting a release in a week or two.

**Comment by kenwdelong** [comment]
That looks brilliant - I was vaguely thinking of something like this late last night while writing horrible reflection code to access private variables!  :-)

I'd like to  ask for one more piece: could you do exactly the same thing in the "verb" blocks?  Specifically, before `client.execute(request, new Handler(requestConfig), context(requestConfig))` in `ApacheHttpConfig.exec()`.

The reason is, for my crazy use case (I am testing my OAuth2 flow - for some requests I want to follow redirects, for others I don't), I need to set `redirectsEnabled` on a request-by-request basis (I reuse the same `HttpBuilder` instance for the entire test).

So we would end up with code like

    ApacheHttpBuilder.configure {
        request.uri = 'blah'
    }.get {
        client.clientCustomizer {  HttpRequestBase client ->
            RequestConfig.Builder requestBuilder = RequestConfig.custom()
            requestBuilder.setRedirectsEnabled(false)
            client.setConfig(requestBuilder.build())
        }
    }

**Comment by cjstehno** [comment]
Hmm... not sure we can add client configuration at the request level without a lot of refactoring since the client is configured at the global level and shared across requests (remember it also needs to be supported across three different client implementations as well). 

Could you get the same effect with two different HttpBuilder instances (one following redirects and one not)?

Lastly, if you have any good suggestions for our OAuth support, feel free to add them to that issue - it's been just hanging around since neither of us really do much OAuth right now.

**Comment by kenwdelong** [comment]
I see what you mean - `Client` is only available on `HttpObjectConfig`, not in the superclass.  You'd have to move the inner `Client` class up to `HttpConfig`.

But I'm pretty sure I could get it done with two instances as you suggest.  

Looking forward to this release!

As for OAuth, I'll take a look at the ticket.  This work originated as I was trying to migrate from http-builder to http-builder-ng, and it was my OAuth test classes from long ago that broke horribly.

**Comment by cjstehno** [comment]
I am going to close this - I will be cutting a release (0.17.0) by Monday - keep an eye on our twitter feed for notification.
