### ISSUE TITLE
Not possible to use special characters in the URL

### ISSUE THREAD

**Issue by elinger** [http-builder-ng/http-builder-ng#153]
Example: 
When trying to issue a request to http://localhost:8080/api/permissions///user123, the request fails because the middle slash is not encoded. 
It won't work with http://localhost:8080/api/permissions/%2F/user123 either, because % gets encoded, and the target URI becomes http://localhost:8080/api/permissions/%252f/user123

The problem is that groovyx.net.http.UriBuilder.toURI() always uses the URI constructor with multiple params instead of the constructor with String only (this one should be used in case the url String is already encoded).

See also https://stackoverflow.com/questions/4858108/url-to-uri-encoding-changes-a-3d-to-253d?rq=1

**Comment by cjstehno** [comment]
@elinger, can you provide an example configuration for what you are talking about? I created the following test and it passes against all three clients:

```groovy
def 'special characters in uri'() {
    setup:
    ersatzServer.expectations {
        get('/api/permissions///user123').called(1).responds().content(OK_TEXT, TEXT_PLAIN)
    }

    when:
    def result = httpBuilder("${ersatzServer.httpUrl}/api/permissions///user123").get()

    then:
    result == OK_TEXT
}
```

Maybe I am missing something. Also please let me know which client implementation you are using (just in case).

**Comment by elinger** [comment]
@cjstehno I also tried with WireMock and simple Spring Boot Web app and I couldn't reproduce the issue.

Therefore, I will describe the concrete problem that I have. I am trying to define permissions for a user in RabbitMq by issuing the following request:
```
curl -X PUT \
  http://localhost:8080/api/permissions/%2F/guest \
  -H 'authorization: Basic Z3Vlc3Q6Z3Vlc3Q=' \
  -H 'content-type: application/json' \
  -d '{
	"configure":".*",
	"write":".*",
	"read":".*"
}' -v
```
RabbitMq can be easily started locally with docker:
```
docker run -d --hostname lab-rabbit --name lab-rabbit -p 8080:15672 -p 5672:5672 rabbitmq:3-management
```
No additional actions are needed, just start RabbitMq with docker and send the request. The response should be 204.

I am not able to send a request with groovy which is equivalent to the curl one.

**Comment by cjstehno** [comment]
Are you sure this is not a problem on the server side? Also, again, we would need an example of what you are using as your HttpBuilder config.

**Comment by elinger** [comment]
I am not sure that it is not also a server side issue. 
But I claim that I it works when I use postman or curl to send the requests, and that I cannot create equivalent request with http-builder-ng-core. 

Here ist the the code that I am using:
```
import groovy.json.internal.Charsets
import groovyx.net.http.HttpBuilder

import static groovyx.net.http.HttpBuilder.configure

def HttpBuilder http = configure {
    request.uri = 'http://localhost:8080'
    request.auth.basic 'guest', 'guest'
    request.contentType = 'application/json'
    request.charset = Charsets.UTF_8
}

@groovy.transform.Canonical
class CreatePermissionsReqBody {
    String configure
    String write
    String read
}


println "> Create permissions for guest"

http.put(Object) {
    request.uri.path = "/api/permissions///guest"
//    request.uri.path = "/api/permissions/%2F/guest"

    request.body = new CreatePermissionsReqBody(
            configure: '.*',
            write: '.*',
            read: '.*')

    response.success { fromServer, responseBody ->
        if (fromServer.statusCode == 201) {
            println "Permissions created"
        } else if (fromServer.statusCode == 204) {
            println "Permissions updated"
        } else {
            println "Unexpected response: $fromServer.statusCode, ${fromServer.message}, ${fromServer.getHeaders()}"

        }
    }

    response.failure { fromServer, resBody ->
        println "Request failed. Status: $fromServer.statusCode, Body: $resBody"
    }
}

```

**Comment by cjstehno** [comment]
Unless you can provide a failing unit test reproducing this issue, I don't feel it's a problem on the client side. I am closing this issue - feel free to reopen it if you have more information.
