### ISSUE TITLE
Possible to change configuration?

### ISSUE THREAD

**Issue by TobiX** [http-builder-ng/http-builder-ng#154]
Currently it seems to be impossible to update/change the configuration of an already created HttpBuilder. This seems like a conscious design decision and is probably a GOOD THING. But sometimes I might want to change the configuration of an HttpBuilder. Would it be possible to provide a "configure" method which takes an existing HttpBuilder as a template and creates a new one with additional options?

**Comment by cjstehno** [comment]
Sounds like an interesting idea. I could see the copy approach being useful... something like:

```groovy
HttpBuilder http = otherHttp.configure {
    // alternate config that overrides specified original values 
}
```

**Comment by TobiX** [comment]
Except I can't use the method name "configure", since that would collide with the static method 🙄 

How about "rebuild", "copy", "extend" or something like that... (` clone` is already taken 😈)

**Comment by cjstehno** [comment]
Ah, yeah, good point. Let's go with copy.

**Comment by cjstehno** [comment]
Just to confirm... are you implementing this? If so, please branch off the `development` branch. Thanks.

**Comment by TobiX** [comment]
I'll try ;) Will do.

**Comment by cjstehno** [comment]
@TobiX are you still considering this? Just checking because I may have some free time to look at issues soon.

**Comment by TobiX** [comment]
I started with a prototype but then was too busy to continue with it. I might be able to whip up something this weekend...

**Comment by cjstehno** [comment]
After thinking about this a bit more, I am not sure it's worth the risk at this point. My concern is that it would be too easy to get into odd configuration situations with difficult to trace bugs due to the multi-layered configuration approach. On top of that I am not sure how much value there is when you _can_ just share closures or consumers between multiple clients.

**Comment by TobiX** [comment]
I'll take a look if that approach also works in my use case.
