### ISSUE TITLE
Support for http2

### ISSUE THREAD

**Issue by cjstehno** [http-builder-ng/http-builder-ng#171]
Figure out which clients support it. I think only OkHttp. Then figure out how best to expose it as a configuation option.

**Comment by cjstehno** [comment]
Ouch. Http/2 seems a bit more painful than expected. I am working on adding http/2 support to Ersatz (see https://github.com/cjstehno/ersatz/issues/73) but there are currently issues that require more research.

**Comment by dwclark** [comment]
Yeah, http/2 really is nothing like http 1.0.

**Comment by cjstehno** [comment]
Nobody seems to be asking for this so I am going to close it until someone wants it.
