### ISSUE TITLE
Cannot add Authorization header

### ISSUE THREAD

**Issue by verglor** [http-builder-ng/http-builder-ng#175]
It is impossible do define custom Authorization request header:
```
            HttpBuilder.configure {
                request.uri = url
                request.headers['Authorization'] = "Bearer ${token}".toString()
            }.put()
```
It seems problem is in underlying URLConnection: https://stackoverflow.com/q/2026260

**Comment by cjstehno** [comment]
If the problem is in the UrlConnection we probably won't be able to do anything about it. Can you use the Apache or OkHttp client implementation instead?

**Comment by verglor** [comment]
I have found out that the header is actually send, just `URLConnection.getRequestProperties()` does not return it so it is not logged by `JavaHttpBuilder`. Probably due to security reasons.
