### ISSUE TITLE
Request headers have to be explicitly casted to String

### ISSUE THREAD

**Issue by verglor** [http-builder-ng/http-builder-ng#176]
The following assignment throws ClassCastException:
`request.headers['Authorization'] = "Bearer ${token}"`
One has to explicitly cast it to String which is not so groovy:
`request.headers['Authorization'] = "Bearer ${token}".toString()`

**Comment by cjstehno** [comment]
I have a fix for this and will be cutting a release (v1.0.2) on Friday. 

The header map will now be defined as `Map<String,CharSequence>` to account for both String and GString (since both implement it).
