### ISSUE TITLE
Query parameters not url encoded

### ISSUE THREAD

**Issue by erdna** [http-builder-ng/http-builder-ng#188]
I set the url parameter via:

`request.uri.query = [username         : email]`

and in the final URI the username contains an + and an @. I assume that this must be replaced by `%40` and `%2B`. The funny thing is. If I do that under my own with `java.net.URLEncoder.encode` it is double encoded! For me its then working when I set `request.uri.useRawValues = true`

**Comment by cjstehno** [comment]
This is the expected behavior

**Comment by cjstehno** [comment]
See https://http-builder-ng.github.io/http-builder-ng/asciidoc/html5/#_encoded_uri_path for more information

**Comment by erdna** [comment]
@cjstehno Thanks for the amazing fast reply. But why is it encoded if I encoded it on my own before?
