### ISSUE TITLE
Sending request body (entity) with GET request

### ISSUE THREAD

**Issue by kenwdelong** [http-builder-ng/http-builder-ng#189]
Does the library support request bodies (entities) when using GET requests?

I have been playing around with variations like this:

		http.get() {
			request.uri.path = serviceUri
			if(params) request.uri.query = params
			if(token) request.headers."$headerName" = token
			if(body) {
				request.body = body
				request.contentType = 'application/json'
				request.charset = 'UTF-8'
			}
			response.success  successHandler
			response.failure  failureHandler
		}

but so far it does not appear to be sending the request body.  My (Spring Boot) server is reporting "Unreadable request: Required request body is missing"

**Comment by cjstehno** [comment]
Sorry, GET requests dont support request body content. You should consider using POST or PUT, or passing everything as request parameters.
