### ISSUE TITLE
Is HttpBuilder thread safe?

### ISSUE THREAD

**Issue by WalterInSH** [http-builder-ng/http-builder-ng#192]
Hi

Thanks for you work. Http builder ng has been my first option for a long time.
I'm wondering if HttpBuilder is thread safe?
Can I define a static filed like this?

```
static def http = HttpBuilder.configure {}
```

**Comment by cjstehno** [comment]
Yes.

**Comment by WalterInSH** [comment]
@cjstehno Thanks!!
