### ISSUE TITLE
Can't access body in success response handler

### ISSUE THREAD

**Issue by wheelerlaw** [http-builder-ng/http-builder-ng#199]
I am trying to get the body of the response in the `success` response handler, however, I keep getting "Stream closed" IOExceptions. How do I get the body of the response in the response handler?

Something like this:
```groovy
def parentId = HttpBuilder.configure {
	request.uri = "http://$xlrHost"
	request.headers["Authorization"] = "Basic ${"$xlrUsername:$xlrPassword".bytes.encodeBase64().toString()}"
}.get {
	request.uri.path = "/api/v1/folders/find"
	request.uri.query = [byPath: parentPath]
	response.when(404) {
		""
	}
	response.success {FromServer fs ->
		(new JsonSlurper().parse(fs.inputStream.text)).fieldA
	}
}
```

The javadocs say that the input might have already been parsed (I imagine by `response.parse`), but then how do I get the parsed body? It does not look like there is a field for that in the `fs` object.

**Comment by wheelerlaw** [comment]
Okay, I see now that it is the second parameter for the status handler closure. I edited the documentation to better reflect this in the code sample (I missed the sentence immediately before it).

**Comment by cjstehno** [comment]
There is a second parameter passed to the closure, which should be the body content. It's not well documented, but if you look at the Java version of the method you can see that its a BiConsumer - the closure is the same.

Let me know if this resolves your issue and I will convert this to a documentation issue.

NOTE: looks like you just saw it.
