### ISSUE TITLE
Example of using multipart with an input stream

### ISSUE THREAD

**Issue by wheelerlaw** [http-builder-ng/http-builder-ng#201]
So I am trying to upload a file using `multipart`. I noticed that the signature accepts an `Object` as the last argument, but the documentation only has an example of passing a `File` into that argument. I am trying to use some sort of stream (either and OutputStream or InputStream), so I don't need to write anything to disk. Are there any examples on how to do this? I'm trying to dig through the source code, but I'm not having any luck extrapolating anything. Thanks.

**Comment by cjstehno** [comment]
I have not been in that area of the code in a bit, but I seem to remember that we are lacking stream support for multipart requests. You are welcome to take a crack at it :-)

**Comment by wheelerlaw** [comment]
Okay, so it looks like it works flawlessly. Here is my small example of reading files into a ZipOutputStream and then piping that into a ByteArrayInputStream to be read by the `multipart` block. 

```groovy
def xlr = HttpBuilder.configure {
    request.uri = "http://$xlrHost"
    request.headers["Authorization"] = "Basic ${"$xlrUsername:$xlrPassword".bytes.encodeBase64().toString()}"
}

def zip = new ZipOutputStream(baos)

zip.putNextEntry(new ZipEntry("release-template.json"))
zip.write(new JsonBuilder(templateJson).toString().getBytes("UTF-8"))
zip.closeEntry()

zip.putNextEntry(new ZipEntry("manifest.json"))
zip.write('{"xlr-data-model-version":"7.5.0#3","xlr-version":"7.5.2"}'.getBytes("UTF-8"))
zip.closeEntry()

// Put required attachments in the ZIP, if any.
fileTree(dir: template.file.path, include: 'attachments/').visit { FileTreeElement attachment ->
    if(!attachment.isDirectory()){
        zip.putNextEntry(new ZipEntry(attachment.relativePath.toString()))
        zip.write(attachment.file.bytes)
        zip.closeEntry()
    }
}

zip.close()

def bais = new ByteArrayInputStream(baos.toByteArray())

xlr.post {
    request.uri.path = "/upload/templates/zip"
    request.uri.query = [folderId: parentId]
    request.contentType = 'multipart/form-data'
    request.body = MultipartContent.multipart {
        part('file', 'template.xlr', 'application/octet-stream', bais)
    }
```

**Comment by cjstehno** [comment]
Nice! I will leave this open as a documentation issue and will probably steal your example :-) Thanks.

**Comment by cjstehno** [comment]
Documented in 1.1.
