### ISSUE TITLE
multipart - no multipart boundary was found

### ISSUE THREAD

**Issue by ChrLipp** [http-builder-ng/http-builder-ng#202]
Hi,

I want to upload a file, the request ist build like this:

	def builder = configure {
		request.uri = stageUrl
		request.charset = StandardCharsets.UTF_8
		request.contentType = JSON[0]
	}
	builder.post {
		request.uri.path = "/upload"
		request.contentType = 'multipart/form-data'
		request.body = multipart {
			part 'data', filename, 'application/octet-stream', path.toFile()
		}
		request.encoder 'multipart/form-data', CoreEncoders.&multipart

		response.failure {
			throw new RuntimeException('Could not upload')
		}
	}

On the server I get an exception:

    org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found

I turned on DEBUG logging, but the request is not logged (core implementation).

I am not sure if my code is correct, can you point me in the right direction?

**Comment by cjstehno** [comment]
Can you try one of the other client implementations to be sure it's not a core implementation bug?

What type of server are you hitting? What Java and groovy version are you using and what version of the library?

Other than that, review https://http-builder-ng.github.io/http-builder-ng/asciidoc/html5/#_multipart to be sure your code is correct.

**Comment by ChrLipp** [comment]
I tried with http-builder-ng-apache with the CoreEncoders and received the same error. When I use the ApacheEncoders I receive  a null pointer exception:

     Exception in thread "main" java.lang.NullPointerException at groovyx.net.http.util.IoUtils.transfer(IoUtils.java:93)

The server is a Spring Boot application (1.5.4.RELEASE) and works since 3 different clients are using the server, only the grovy implementation has the problems.

Groovy Version: 2.4.9 JVM: 1.8.0_172 Vendor: Oracle Corporation OS: Windows 10

I reviewed the documentation, my example is not ident, I have only one parameter in the form instead of two. When I add a (dummy) second parameter in front I receive the exception:

    org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found

Kind regards, Christian

**Comment by cjstehno** [comment]
Here is a simple working example (attached). One thing to double-check is that you are using the correct `multipart` in the DSL - see the imports in the client runner.

If you feel that there is still a problem, please tweak the provided app to be more representative of your situation.

[demo.zip](https://github.com/http-builder-ng/http-builder-ng/files/2353298/demo.zip)

**Comment by cjstehno** [comment]
Since there has been no further communication I am assuming that the issue was resolved. Please re-open and provide more information if this is not the case.
