### ISSUE TITLE
How to configure to follow redirects

### ISSUE THREAD

**Issue by wheelerlaw** [http-builder-ng/http-builder-ng#203]
It appears that the library does not follow 302 redirects by default. Not a big deal (it would be nice if it did), but I can't seem to find any documentation in the [docs](https://http-builder-ng.github.io/http-builder-ng/asciidoc/html5/) on how to configure it to follow a 302. 

I am using http-builder-ng-apache 1.0.3

Example code:
```groovy
def bitbucket = HttpBuilder.configure {
    request.uri = "http://$bitbucketHostPort"
    request.auth.basic bitbucketUsername, bitbucketPassword
}

bitbucket.get {
    request.uri.path = "/rest/api/1.0/projects/eba/repos"
    response.success { FromServer fs, Object responseBody ->
        println (responseBody)
        println fs.headers
        println fs.statusCode
    }
}
```

Yields this output:
```
null
[Location: https://bitbucket.server.hostname/rest/api/1.0/projects/eba/repos, Server: BigIP, Connection: keep-alive, Content-Length: 0, Proxy-Connection: keep-alive]
302
```

**Comment by cjstehno** [comment]
You need to use a clientCustomizer (see https://http-builder-ng.github.io/http-builder-ng/asciidoc/html5/#_client) to configure this on your underlying client.

**Comment by cjstehno** [comment]
If you come up with the configuration for your client, add it as a note here and I will add it as an example in the user guide. Thanks.

**Comment by wheelerlaw** [comment]
Okay, look like it was an issue with redirecting from HTTP to HTTPS (Java [won't allow it](http://www.cs.mun.ca/jdk1.6/technotes/guides/deployment/deployment-guide/upgrade-guide/article-17.html), even if `followRedirects` is set to true on the HttpUrlConnection). But nonetheless, it would be great to see some documentation around handling redirects in general.

**Comment by cjstehno** [comment]
This has been documented and will be in the 1.1 release.
