### ISSUE TITLE
difficult to handle exceptions

### ISSUE THREAD

**Issue by kgeis** [http-builder-ng/http-builder-ng#39]
I'm finding it difficult to handle exceptions.

First, I think it is unintuitive that a network error throws an exception and does not call the failure method. I realize that the documentation is clear that `.failure(..)` is for valid responses with code > 400, but this does not satisfy the principle of least surprise. Note, it's also different from what `jQuery.ajax()` does.

Also, I'm having trouble catching exceptions because they are wrapped in `RuntimeException`. I think that it is unnecessary to wrap exceptions like this when the code is intended to be called from Groovy. To illustrate this, I want to ignore `SocketException`. Instead of writing

    } catch (SocketException ex) { }

I need to write

    } catch (RuntimeException ex) {
        if (! ex.cause in SocketException) {
            throw ex
        }
    }

**Comment by dwclark** [comment]
There are two reasons we currently wrap exceptions in RuntimeException. The first is personal preference, I simply prefer working with Java code that avoids checked exceptions. The second is practical, we make heavy use of lambdas inside http-builder-ng and lambdas don't play nice with checked exceptions.

I do think there is some justification in being more precise about which unchecked exceptions are re-thrown. Most of the RuntimeExceptions are catching IO exceptions that happen before a response is returned. Maybe we can expand the unchecked exceptions to be more precise about what happened before we receive a response and then use the existing HttpException for post response exceptions.

**Comment by cjstehno** [comment]
@dwclark are you planning on addressing this any further? If not, we should probably close it as a "wont fix".

**Comment by dwclark** [comment]
@cjstehno @kgeis I think I finally have solution that fits with the overall strategy of http-builder-ng and is backwards compatible.

I'm going to introduce a 2 new method in HttpConfig.java called `exception`. One will accept a `Closure`, the other a `Consumer` and they will accept a `Throwable`. The strategy for all exceptions going forward will be to let the actual exception bubble up until it reaches a handler. At that point the handler will call the `exception` method where the user can do whatever they want with the exception.

The default implementation will simply wrap the exception in a `RuntimeException` and then re-throw it. This should make all existing http-builder-ng code work like it always has, but give people who care the chance to log/debug/whatever the exception.

**Comment by kgeis** [comment]
I didn't know how to respond to your earlier comments, but I like the strategy that you've outlined.

**Comment by dwclark** [comment]
Work will be on github-issue-39 branch. Initial plumbing work for exception handling is done. I'll convert the existing exceptions to use the new framework soon (hopefully this week).

**Comment by cjstehno** [comment]
Sounds like a good solution to me.

**Comment by cjstehno** [comment]
This has been merged into the `development` branch and will be in the next release.
