### ISSUE TITLE
Publish code coverage results

### ISSUE THREAD

**Issue by aalmiray** [http-builder-ng/http-builder-ng#45]
The build already has JaCoCo configured. Reports may be published to https://coveralls.io/ and/or https://codecov.io/

Depends on fix for #28

**Comment by cjstehno** [comment]
I have [coveralls setup](https://coveralls.io/github/http-builder-ng/http-builder-ng) and have added a Gradle plugin to do the push to it... just need to get Travis build to pass consistently.
