### ISSUE TITLE
Pull out implementation projects

### ISSUE THREAD

**Issue by cjstehno** [http-builder-ng/http-builder-ng#46]
Pull the alternate implementation clients into separate projects:

* core - the core functionality and common code
* java - the java-internal client
* apache - the apache http components client

**Comment by dwclark** [comment]
Can we leave java/core together? Since there are no additional dependencies having an additional sub project seems unnecessary.

**Comment by cjstehno** [comment]
Sure. Makes sense.

**Comment by dwclark** [comment]
@cjstehno 

One more thing, I do think we should keep the basic configration the same as it is now. This will make it easier to test, keep configuration uniform, and allow people to use multiple clients in the same project (probably not the best idea, but someone's going to try).

Specifically something like:

```
Function apacheBuilder = { c -> new ApacheHttpBuilder(c); } as Function;

httpBin = HttpBuilder.configure(apacheBuilder) {
    request.uri = 'http://httpbin.org/';
}
```

should still be possible. Though each sub library should follow a convention through maybe static imports to allow uniform configuration. Maybe something like:

```
import static groovyx.net.http.ApacheHttpBuilder.factory;

httpBin = HttpBuilder.configure(factory) {
    request.uri = 'http://httpbin.org/';
}
```

which would allow multiple clients to be configured for testing/usage like this:

```
import static groovyx.net.http.ApacheHttpBuilder.factory as apacheFactory;
import static groovyx.net.http.OkHttpBuilder.factory as okHttpFactory;
import static groovyx.net.http.HttpBuilder.factory as javaFactory;

apacheHttpBin = HttpBuilder.configure(apacheFactory) {
    request.uri = 'http://httpbin.org/';
}

okHttpBin = HttpBuilder.configure(okHttpFactory) {
    request.uri = 'http://httpbin.org/';
}

javaHttpBin = HttpBuilder.configure(javaFactory) {
    request.uri = 'http://httpbin.org/';
}
```

**Comment by cjstehno** [comment]
Yep. That is the plan. :-)

**Comment by cjstehno** [comment]
This has been done in `project-split` branch and will test/merge soon.
