### ISSUE TITLE
0.11.0 not released to jcenter

### ISSUE THREAD

**Issue by aaronhagopian** [http-builder-ng/http-builder-ng#59]
The documentation was bumped to 0.11.0 but it looks like the archive was never uploaded to jcenter.

**Comment by cjstehno** [comment]
Are you trying to use the badge link or is it failing to resolve in Gradle/maven build? There is a known issue (fixed in the dev branch) related to the badge being out of date.

**Comment by aaronhagopian** [comment]
gradle is failing is how I found out.  The readme shows you can use the depencency of

`compile 'org.codehaus.groovy.modules:http-builder-ng:0.11.0'`

But on the bintray website it shows only 0.10.2 as the latest.

**Comment by cjstehno** [comment]
Hmm... its published and like I said, the badge is wrong. Let me take a look, maybe I missed a step when the project was split up.

**Comment by cjstehno** [comment]
Yep... looks like I had to request that the "new" sub-project artifacts be added to jcenter. I have submitted the request for both libraries - usually they get added pretty quickly, but I will keep this issue open until then. Also there are some issues with the README that I will go fix right now. 

Thanks for pointing these out!

**Comment by cjstehno** [comment]
As a workaround, you can add:

    maven { url 'https://dl.bintray.com/http-builder-ng/dclark/' }

to your Gradle build repositories config... if you are using Maven, sorry, I don't remember how to do that right now.

**Comment by dwclark** [comment]
@aaronhagopian @cjstehno 

I can now pull both artifacts from bintray. Bin sure to specify either http-builder-ng-core or http-builder-ng-apache. We are separating support for different back ends into different libraries. This is a breaking change from 0.10.x

**Comment by dwclark** [comment]
I am closing this bug. If this issue still is a problem please comment here again and we will take another look.

**Comment by cjstehno** [comment]
Yeah they were published a few hours ago. I will remove the note from the readme tomorrow.
