### ISSUE TITLE
Could not find artifact io.github.http-builder-ng:http-builder-ng-apache:0.13.2

### ISSUE THREAD

**Issue by dacrome** [http-builder-ng/http-builder-ng#76]
Hi,

I try to fetch the artifact with the following Gradle configuration:

```
    dependencies {
        testCompile 'io.github.http-builder-ng:http-builder-ng-apache:0.13.2'
    }

    repositories {
        jcenter()
        mavenLocal()
        mavenCentral()
    }
```

but get the following error:

```
Error:Could not find io.github.http-builder-ng:http-builder-ng-apache:0.13.2.
Searched in the following locations:
    https://jcenter.bintray.com/io/github/http-builder-ng/http-builder-ng-apache/0.13.2/http-builder-ng-apache-0.13.2.pom
    https://jcenter.bintray.com/io/github/http-builder-ng/http-builder-ng-apache/0.13.2/http-builder-ng-apache-0.13.2.jar
    file:/Users/david/.m2/repository/io/github/http-builder-ng/http-builder-ng-apache/0.13.2/http-builder-ng-apache-0.13.2.pom
    file:/Users/david/.m2/repository/io/github/http-builder-ng/http-builder-ng-apache/0.13.2/http-builder-ng-apache-0.13.2.jar
    https://repo1.maven.org/maven2/io/github/http-builder-ng/http-builder-ng-apache/0.13.2/http-builder-ng-apache-0.13.2.pom
    https://repo1.maven.org/maven2/io/github/http-builder-ng/http-builder-ng-apache/0.13.2/http-builder-ng-apache-0.13.2.jar
Required by:
    project :backend
```

I also tried older versions and ask colleagues to use the dependency, but they get the same error.

**Comment by cjstehno** [comment]
Older versions have a different group ID. It changed in 0.13.0 I will take a look at this today. 

I'm willing to bet I need to have bintray sync the new group ID to the jcenter repo. It's a one time manual step I tend to forget with new repos.

**Comment by cjstehno** [comment]
Prior to 0.13.0 it is `org.codehaus.groovy.modules` try the last pre 0.13.0 build with that group ID or try again once I have fixed this (later today).

**Comment by cjstehno** [comment]
I can't change the group name in the JCenter repo sync myself - based on a [SO post](http://stackoverflow.com/questions/34756204/how-to-change-groupid-if-project-is-already-uploaded-to-bintray-and-synced-with) I found, I sent Bintray support an email about fixing our sync with the new Group ID. They generally have a quick turn around so hopefully this will start working before tomorrow morning, if not, I will document a work-around and update any status here.

Thanks for pointing out this issue.

**Comment by cjstehno** [comment]
Ok, new Bintray packages were created for the new group ID. They have been populated with the 0.13.2 release and a request has been submitted to Bintray for inclusion into JCenter - hopefully they respond with their usual quickness.

**Comment by cjstehno** [comment]
They are quick - 0.13.2 is available via JCenter now and I have verified it from a second computer to be sure I didn't have it cached or anything. :-) Closing this out.
