### ISSUE TITLE
incorrect generation of URI with multi-valued query parameters

### ISSUE THREAD

**Issue by kgeis** [http-builder-ng/http-builder-ng#85]
I expect the output to be the same in both of these cases. With UriBuilder, it is different, as you can see.

    @Grab('io.github.http-builder-ng:http-builder-ng-core:0.13.3') 
    import groovyx.net.http.UriBuilder
    
    def testURL = 'http://test.com/a?b=c&d=e'
    
    println new URI(testURL)
    println UriBuilder.basic(UriBuilder.root()).setFull(testURL).toURI()

output:

    http://test.com/a?b=c&d=e
    http://test.com/a?b=[c]&d=[e]

**Comment by cjstehno** [comment]
Fixed in development branch for pending 0.14.0 release.
