### ISSUE TITLE
clarify docs: must specify JSoup dependency to get default HTML parser

### ISSUE THREAD

**Issue by kgeis** [http-builder-ng/http-builder-ng#87]
I tried the following script

    @Grab('io.github.http-builder-ng:http-builder-ng-core:0.13.3')
    @Grab('org.apache.commons:commons-lang3:3.5')
    
    import groovyx.net.http.HttpBuilder
    
    HttpBuilder.configure{
        request.uri = 'https://google.com/'
    }.get{
        response.success{ resp, html ->
            println resp.contentType
            println html.getClass().name
        }
    }

I was confused to have the response come back as a byte array. The documentation says:

> Default parsers are provided for: HTML (org.jsoup.nodes.Document),...

The way it is worded, I would not expect to need to add JSoup to the classpath in order to parse HTML. When I added JSoup to the classpath, then the response came back as a Document.

**Comment by cjstehno** [comment]
Good catch, yes this also came up in our recent user group presentation and I forgot to make an issue for it. I'll update the encoder/decoder support docs. Thanks.

**Comment by cjstehno** [comment]
This has been addressed in the 0.14.0 release (development branch)
