### ISSUE TITLE
URI query ignored when specified in configure block

### ISSUE THREAD

**Issue by kgeis** [http-builder-ng/http-builder-ng#88]
I expect these requests to be equivalent, but they are not. The first way does not send query parameters.

    @Grab('io.github.http-builder-ng:http-builder-ng-core:0.13.3')
    @Grab('org.apache.commons:commons-lang3:3.5')
    @Grab('org.jsoup:jsoup:1.10.2')
    
    import groovyx.net.http.HttpBuilder
    
    println HttpBuilder.configure{
        request.uri = 'http://urlecho.appspot.com/echo?status=200&Content-Type=text%2Fhtml&body=Hello%20world!'
    }.get()
    
    println HttpBuilder.configure{
        request.uri = 'http://urlecho.appspot.com/echo'
    }.get{
        request.uri.query = [status: '200', 'Content-Type': 'text/html', body: 'Hello world!']
    }

According to my reading of the documentation, the first way is valid, and it's more straightforward.

**Comment by cjstehno** [comment]
You are correct that this should be supported. We'll take a look.

**Comment by cjstehno** [comment]
Fixed in the development branch, pending 0.14.0 release.
