### ISSUE TITLE
Add support for proxying connections

### ISSUE THREAD

**Issue by dwclark** [http-builder-ng/http-builder-ng#90]
We have a request for Http Builder NG to support proxying connections. All of our supported clients have this feature (though of course implemented differently). We should add a proxy property at the request configuration level and then properly use it in the clients.

**Comment by dwclark** [comment]
@cjstehno So I have done the research to implement this for all three clients. However, I have no idea how to test this. Any ideas? All seem fairly simple. We could just set the properties and assume it is correct, which of course is wrong. But, I don't know what the right thing looks like in this case.

**Comment by cjstehno** [comment]
I have an idea about how to test it...  I sent you an email and we can talk at the meeting tomorrow.

**Comment by cjstehno** [comment]
@dwclark when you have a chance to prototype proxy support on at least one of the clients, let me know - I think this should be fairly straight-forward to test, but I need something to test to be sure. :-)

**Comment by twogee** [comment]
:+1:

**Comment by dwclark** [comment]
@twogee My intent is to have all of the proxy connections be per-request. What do you mean by "implementation-specific way"? Each of the underlying libraries (java core, apache, okhttp) does proxying in its own way. The idea is for a general proxy configuration to do the right thing in all cases.

**Comment by dwclark** [comment]
@cjstehno I should be able to work on this this week. Vacation is over and the critical bug fix I had at work is complete now.

**Comment by twogee** [comment]
Sorry for being unclear, I meant to try setting up proxies with the current release. Hope the generic configuration will be available soon. 🙏

**Comment by cjstehno** [comment]
@dwclark ok, let me know when you have at least one of them implemented and I will get the support into Ersatz for testing - I know what I need to do and its pretty easy but I want to ensure that what I have lines up with how it will be used. Thanks.

**Comment by cjstehno** [comment]
I don't think I need to do anything extra to support testing for proxied connections. You can just use two Ersatz servers (one the proxy and one the "original") then just ensure that the proxy gets your requests and not the real server... here is a test I added to Ersatz to test this (using OkHttp) - it's just a snippet, so missing some general config:

```groovy
def 'proxied request should return proxy not original'(){
    setup:
    ErsatzServer proxyServer = new ErsatzServer({ autoStart() })
    proxyServer.expectations {
        get('/proxied').called(1).responds().content('forwarded').code(200)
    }

    ersatzServer.expectations {
        get('/proxied').called(0).responds().content('original').code(200)
    }

    OkHttpClient proxiedClient = new OkHttpClient.Builder()
        .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress('localhost', proxyServer.httpPort)))
        .cookieJar(new InMemoryCookieJar())
        .build()

    when:
    okhttp3.Response response = proxiedClient.newCall(new okhttp3.Request.Builder().get().url(url('/proxied')).build()).execute()

    then:
    response.code() == 200
    response.body().bytes() == 'forwarded'.bytes

    and:
    proxyServer.verify()
    ersatzServer.verify()
}
```

If this does not adequately test the proxy stuff, let me know and we can figure out what's missing.

**Comment by thadguidry** [comment]
Hurry up with this. :) We also have a need.

**Comment by cjstehno** [comment]
@dwclark are you still working on this or do you want me to take it?

**Comment by dwclark** [comment]
@cjstehno I have a partial implementation on a local branch. If I can't finish it up tonight/tomorrow you can take it over. Hopefully I can finish up a few minor issues for a 0.18 release as well.

I feel bad this keeps getting side tracked. My excuses are legit. First there was the need to switch jobs. Now that is fixed, but I have family that are hurricane Harvey refugees in my house and I'm helping out with that. That should be stabilized by this evening and I can get some work done.

**Comment by thadguidry** [comment]
@dwclark Kudos to you for helping out David. I'm in Plano @Ericsson

**Comment by cjstehno** [comment]
@dwclark I haven't done much either, and I don't have any of your excuses. :-)

**Comment by dwclark** [comment]
@cjstehno 

Proxy support is done, pending review, merge, and final build:

https://github.com/http-builder-ng/http-builder-ng/pull/158

I have tested the implementation, but you will notice that the proxy tests are currently ignored. The reason for this is that I had to set up proxies on my dev machine to test them. There are issues we will need to deal with to enable automatic testing and it may not be feasible to have automatic tests in all cases.

Basically we have four cases. The proxy server can either be HTTP level or SOCKS level. The proxied server can be running either HTTP or HTTPS. All possible combos means 4 tests. I have coded all of the tests and can run 3 of them. Here are the states of the combinations:

Proxy SOCKS/Proxied HTTP: Can test this by placing ssh into SOCKS proxy mode. Works fine but requires ssh to be running locally.

Proxy SOCKS/Proxied HTTPS: Same as previous

Proxy HTTP/Proxied HTTP: I have tested this using tinyproxy, an HTTP level proxy. This requires a working installation of tinyproxy. This test is the one we can currently automate if we add functionality to ersatz. Basically ersatz/Undertow has to be put into proxy mode so that all inbound connections are forwarded/proxied to a second running instance of ersatz/Undertow. The code sample you provided above is the opposite test of what we want. `response.body().bytes() == 'forwarded'.bytes` should be `response.body().bytes() == 'original'.bytes` to show proxying working correctly. To make the test complete, there should also be an assert that both the proxy and the proxied server were called the exact same number of times.

Proxy HTTP/Proxied HTTPS: Curently Undertow cannot support this configuration. I have noted this in the proxy tests along with the Undertow JIRA issue explaining what they need to support to allow Undertow to support this combo.

**Comment by cjstehno** [comment]
Hmm... I thought all we'd need for Ersatz was what was in the example above (for the HTTP proxy). I guess my limited knowledge of proxying has failed me! :-) I think I was more testing that you hit the server you expected and then trusted that the server and underlying clients both did the right thing. Setting up real proxies in the embedded Ersatz undertow was a bit of a pain. It would probably be easier to create a little helper server (in Ersatz I guess) that would be an embedded proxy server to replace tinyproxy... do you think that would work?

**Comment by cjstehno** [comment]
Would this help for testing SOCKS (https://github.com/ravn/jsocks/blob/master/jsocks_code1.01/socks/ProxyServer.java)?

**Comment by thadguidry** [comment]
@dwclark Sweet David.  Nice Job :)  :1st_place_medal:

**Comment by dwclark** [comment]
@cjstehno That would work for SOCKS testing, provided that project still compiles and works :-)

**Comment by cjstehno** [comment]
@dwclark I will give it a try soon and see if we can get more of the tests automated.

**Comment by cjstehno** [comment]
This has been implemented in the `development` branch and will be part of the 0.18.0 release.

**Comment by cjstehno** [comment]
@dwclark I have a standalone proxy server component in Ersatz that will be coming with the next release. I will make sure it works with your tests and then use it instead of the external app. I will look into the socks replacement later (created an issue for it).

**Comment by dwclark** [comment]
@cjstehno Thanks, ask me if anything is unclear. Half of the problem with proxies is understanding what they do.
