### ISSUE TITLE
Need access to 40x responses

### ISSUE THREAD

**Issue by cgorshing** [http-builder-ng/http-builder-ng#93]
I don't have a lot of experience with this project (1 day only), so there might be other ways to handle a 401, so please correct me if there are.

But in JavaHttpBuilder, I think we need more work around the JavaFromServer constructor. The HttpURLConnection.getInputStream throws an exception when the response was a 401. This goes into the catch statement and gets swallowed. See http://download.java.net/jdk7/archive/b123/docs/api/java/net/HttpURLConnection.html#getErrorStream() for info on the getErrorStream call.

I would like to have a logger in that catch statement so I could have adjusted some logging and found the root cause.

Also I've got my own copy locally and made these changes.
```
InputStream connectedStream = null;
try {
  connectedStream = connection.getInputStream();
}
catch (IOException e) {
  BufferedReader input = new BufferedReader( new InputStreamReader(connection.getErrorStream()) );
  String inputLine;
  StringBuffer response = new StringBuffer();

  while ((inputLine = input.readLine()) != null) {
     response.append(inputLine);
  }
  input.close();

  failedBody = response.toString();
}

BufferedInputStream bis = new BufferedInputStream(connectedStream);
```

This allows me to get at the "failedBody" within my client code. I would love some feedback and would be happy to submit a PR, but I wanted opinions first.

**Comment by cjstehno** [comment]
Go ahead and create a PR with your changes and we can go from there. This seems like it might be useful, but I am not quite sure where it fit in... easier to see in code.

**Comment by dwclark** [comment]
@cjstehno It looks like I have known about this problem for sometime: https://github.com/http-builder-ng/http-builder-ng/blob/0c587f85ca501411791d417f42fe2810e1cefab6/http-builder-ng-core/src/main/java/groovyx/net/http/JavaHttpBuilder.java#L161

Git blame doesn't lie (unfortunately).

@cgorshing The general approach you suggest is correct. The constructor needs to also handle any encoding the server sends (gzip/deflate) which I don't think you show. Prior to the code it also would need to handle headers and cookies. That code can be shared with the case of no errors.

I believe that the ApacheHttpBuilder does handle this correctly, but I'm not 100% sure. If you can use that it may provide a workaround.

In any case we should include a test for each Builder for this use case.

**Comment by dwclark** [comment]
@cjstehno Can you review the PR I created for this issue and merge?

**Comment by dwclark** [comment]
@cgorshing I just created a pull request which will make the status code, headers, and body available to failure handlers for users of the JavaHttpBuilder. Basically the entire status of the response will be available. You can access this information using a standard response failure handler and put your loggers there. Something like this:

```
def client = JavaHttpBuilder.configure {
  request.uri = "http://www.google.com"
  response.failure { FromServer fs, Object body ->
    log.error("What gives google?, Status Code: ${fs.statusCode}, Body: ${body}")
  }
}
```

Which would log every error coming back to the client.

**Comment by cjstehno** [comment]
@dwclark sure, I will merge it in the morning. I'd like to hold off on a release until we have a couple more fixes in - probably this weekend or early next week. Unless you feel we should get this out sooner.

**Comment by cjstehno** [comment]
This has been addressed and merged into the `development` branch - it will ride along with the next release. Unless the OP indicates that this is critical, it will probably be released within the next week or two.

**Comment by radarsh** [comment]
@cjstehno do you have a rough ETA for the next release containing this fix? Thanks.

**Comment by cjstehno** [comment]
It's been available for a while now... you can just use the current release.
