### ISSUE TITLE
Add import statement to documentation

### ISSUE THREAD

**Issue by psiegman** [http-builder-ng/http-builder-ng#95]
It would be handy to have the import statement in the examples.
I found import groovyx.net.http.HttpBuilder by going to the javadocs, but adding this to the documentation would have saved time.

Thanks for a nice library !

regards,
                  Paul

**Comment by cjstehno** [comment]
Fair enough. I will add them in the next release. Thanks.

**Comment by cjstehno** [comment]
I have added some imports to the examples in the User Guide (will be in v0.14.1 today); however, I think it would be good to have the examples at the end of the guide converted to self-contained Groovy scripts with Grapes to pull in dependencies. I will leave this issue open to track.

**Comment by psiegman** [comment]
That sounds really cool, thanks !

regards,
                        Paul

**Comment by cjstehno** [comment]
Just a note for when I work on this: consider writing the examples in such a way that they can be parsed by a test (from the documentation) and verified to compile and run - this will keep them working and valid.

As a stretch goal it would be interesting if something similar could be done with the rest of the user guide examples and possibly even the javadoc examples. Something reminiscent of Elixir doctests.

**Comment by psiegman** [comment]
This example made it work for me:
https://www.leveluplunch.com/groovy/examples/make-get-request-httpbuilder-apache-httpcomponents/

**Comment by cjstehno** [comment]
@psiegman you realize that is the old HttpBuilder, not HttpBuilder-NG... just to be clear.

**Comment by psiegman** [comment]
Yep, I know.

regards,
                    Paul

**Comment by cjstehno** [comment]
I have replaced most of the full examples in the User Guide with stand-alone scripts (`development` branch). There are a few issues with them for which I have filed separate issue tickets. I am going to close this out.
