### ISSUE TITLE
Cookie Repository Still Blocks Under High Contention

### ISSUE THREAD

**Issue by dwclark** [http-builder-ng/http-builder-ng#96]
Updating a cookie over and over again on multiple threads blocks too often inside the NonBlockingCookieStore, which of course shouldn't happen given the name of the class. Need to figure out why this happens and fix it.

The real culprit is the fact that they default client configuration will always add "global" cookies to the store for each request. One solution is to have a tiered version of the cookie store which adds these globals to a temporary map and thus removes all contention. A second is to reconfigure the concurrent hash map and/or update more carefully during the NonBlockingCookieStore.add method.

**Comment by cjstehno** [comment]
This is fixed in 0.14.1
